# Generated by Django 5.0.6 on 2024-05-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id_avance', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('porcentaje_avance', models.IntegerField()),
                ('documento_avance_url', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('tema_tesis', models.CharField(blank=True, max_length=50, null=True)),
                ('id_carrera_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='tasks.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('id_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='tasks.tutor')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AddField(
            model_name='avance',
            name='id_estudiante_pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='tasks.estudiante'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_facultad_pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='tasks.facultad'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_tutor_pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='tasks.tutor'),
        ),
    ]
